# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-03 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.IntegerField()),
                ('time_stamp', models.IntegerField()),
                ('temp', models.DecimalField(decimal_places=1, max_digits=3)),
                ('hum', models.DecimalField(decimal_places=1, max_digits=3)),
                ('bar', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
    ]
