# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-05 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170103_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='focus',
            field=models.BooleanField(default=False),
        ),
    ]
