# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170108_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='current_time_stamp',
            field=models.IntegerField(default=1),
        ),
    ]
