# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170108_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='current_bar',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='device',
            name='current_hum',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='device',
            name='current_lux',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='device',
            name='current_temp',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
    ]
